[versions]
kotlin = "2.3.0"
ktlint = "14.0.1"
spring = "3.5.4"
spring-dependencies = "1.1.7"
arrow-kt = "2.2.1.1"
graphql-kotlin = "9.0.0-alpha.8"
jooq = "3.20.10"
okhttp = "5.3.2"
resilience4j = "2.3.0"
mockk = "1.14.7"
logback = "1.5.24"
kotest = "5.9.1"
kotest-extensions-arrow = "2.0.0"
kover = "0.9.4"

[libraries]
arrow-fx-coroutines = { group = "io.arrow-kt", name = "arrow-fx-coroutines", version.ref = "arrow-kt" }
arrow-resilience = { group = "io.arrow-kt", name = "arrow-resilience", version.ref = "arrow-kt" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }
logback-core = { group = "ch.qos.logback", name = "logback-core", version.ref = "logback" }
graphql-kotlin-spring-server = { group = "com.expediagroup", name = "graphql-kotlin-spring-server", version.ref = "graphql-kotlin" }
graphql-kotlin-hooks-provider = { group = "com.expediagroup", name = "graphql-kotlin-hooks-provider", version.ref = "graphql-kotlin" }
jooq = { group = "org.jooq", name = "jooq", version.ref = "jooq" }
jooq-kotlin = { group = "org.jooq", name = "jooq-kotlin", version.ref = "jooq" }
flyway-database-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql" }
resilience4j-kotlin = { group = "io.github.resilience4j", name = "resilience4j-kotlin", version.ref = "resilience4j" }
resilience4j-retry = { group = "io.github.resilience4j", name = "resilience4j-retry", version.ref = "resilience4j" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
# Test libraries
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test" }
kotest-assertions-core = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-arrow = { group = "io.kotest.extensions", name = "kotest-assertions-arrow", version.ref = "kotest-extensions-arrow" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
spring = { id = "org.springframework.boot", version.ref = "spring" }
spring-dependencies = { id = "io.spring.dependency-management", version.ref = "spring-dependencies" }
graphql = { id = "com.expediagroup.graphql", version.ref = "graphql-kotlin" }
jooq-codegen = { id = "org.jooq.jooq-codegen-gradle", version.ref = "jooq" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
