name: clean_architecture_kotlin
services:
  postgres:
    image: postgres:18-alpine
    restart: always
    ports:
      - "6685:5432"
    environment:
      POSTGRES_USER: ca_kotlin
      POSTGRES_PASSWORD: ca_kotlin
      POSTGRES_DB: ca_kotlin
